### ISSUE TITLE
Update full-page onboarding to reflect Figma layout

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/stacks-wallet-web#1186]
In Brave I'm seeing the navigation header fall onto its own line whereas it should share the same as the back button:

<img width="1278" alt="Screen Shot 2021-05-18 at 12 46 40" src="https://user-images.githubusercontent.com/28991/118795968-6e9a9c00-b89b-11eb-88b8-0fac25d24e78.png">
<img width="392" alt="Screen Shot 2021-05-18 at 12 47 30" src="https://user-images.githubusercontent.com/28991/118795983-72c6b980-b89b-11eb-9adc-673d2ebeb809.png">

**Comment by andresgalante** [comment]
I'd love to know what's Brave usage, their market share is tiny but it might be larger for our users.

Is it possible to add headers to detect it?

**Comment by aulneau** [comment]
I don't believe this is unique to brave? this is how it works in any of the browsers and was intentional. See screenshot from figma: 

![Screen Shot 2021-05-19 at 7 51 04 AM](https://user-images.githubusercontent.com/11803153/118815615-fde18880-b876-11eb-8b6c-eab60670f0fb.png)

**Comment by markmhendrickson** [comment]
[Looking at the Figma](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/Wallet-%F0%9F%8C%90-web?node-id=1844%3A40464), it appears as though the header is supposed to go into the center with the content within wider viewpoints:

![image](https://user-images.githubusercontent.com/28991/118822446-7452aa80-b8b8-11eb-8f6d-4bd87f5dba72.png)

Though you're right that it should go onto its own line across browsers within thinner / extension popup viewports.

**Comment by markmhendrickson** [comment]
@andresgalante It seems with [our standardized header work to date](https://github.com/blockstack/stacks-wallet-web/issues/1094) that we're tracking OS but not browser / user agent. I imagine we could add a header for that as well. Want to add an issue?

**Comment by aulneau** [comment]
> [Looking at the Figma](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/Wallet-%F0%9F%8C%90-web?node-id=1844%3A40464), it appears as though the header is supposed to go into the center with the content within wider viewpoints:
> 
> ![image](https://user-images.githubusercontent.com/28991/118822446-7452aa80-b8b8-11eb-8f6d-4bd87f5dba72.png)
> 
> Though you're right that it should go onto its own line across browsers within thinner / extension popup viewports.

I think a better issue to have would be "Update full-page onboarding to reflect figma". Currently we use the same design/components for any of the views, so the work that needs to be done is to create variants based on context (full-page, pop-out and popup window).
