### ISSUE TITLE
Transactions that have been confirmed remain as Queued in the Activity tab list

### ISSUE THREAD

**Issue by FriendsFerdinand** [blockstack/stacks-wallet-web#1783]
When looking at my Activity Tab on the wallet, I can see transactions that have already been confirmed as both Confirmed and Queued. Here, you can see the 3 Queued transactions, but below, they are confirmed.
![image](https://user-images.githubusercontent.com/35247240/136295423-7903e96c-65e9-496c-af0a-23c36fb12690.png)

I checked and the Queued transactions map 1-to-1 with the Confirmed transactions.

I am using the Web wallet `v2.19.2` on Firefox `92.0.1`

P.S. I cleared the Firefox cache to see if it would have an effect, but nothing changed.

**Comment by markmhendrickson** [comment]
We just released `v2.19.3` that should resolve this issue. It should update automatically for Firefox, but if not, you can manually reinstall to update.

Mind checking to see if your problem persists here once upgraded?

**Comment by FriendsFerdinand** [comment]
I updated to `v2.19.3` and it's no longer there.

Thank you!
