### ISSUE TITLE
Investigation:Missing Queued token -Reappeared

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/stacks-wallet-web#1786]
User was testing:#1747
This was on Testnet
Transfered Stella token to account 2,saw the token being queued.
I selected the refresh button and suddenly there were no queued token.
Todays transaction in activity was all of sudden empty as well
Also attaching the error message which I saw in console

Note:Will try to reproduce it again.Believe it happened as the first tx of the day

Then I resend another Stella token and saw it being queued and when I refreshed it ,it went to confirmed state quickly
All of sudden am seeing the missing Stella token reappeared in Todays activity 
<img width="720" alt="Screen Shot 2021-10-07 at 1 48 17 PM" src="https://user-images.githubusercontent.com/38872890/136437679-dd3a202e-9c81-432e-a1a9-cfe9af85c8c7.png">
<img width="1284" alt="Screen Shot 2021-10-07 at 1 47 52 PM" src="https://user-images.githubusercontent.com/38872890/136437705-62e75e18-a6d8-4478-8e8c-d8f5d17464ee.png">

cc @beguene @fbwoolf

**Comment by fbwoolf** [comment]
@Eshwari007 this is what the queued state means. The transaction just sits in `Queued` until it is moves into another state. It should be quick and not be there long ...and reappear in the `Today` list.

**Comment by Eshwari007** [comment]
@fbwoolf The first Stella token was `Queued` and then disappeared when I select `'Refresh"` on the screen.
`'Dissappeared'` meant here that the tx was not in any state at all-it was not to be seen in todays activity at all.Just vanished.
It reappeared after sometime when the second Stella token tx was submitted
Second tx was`'Queued -Pending-Confirmed`'accurately

Will try to test couple more times or perform the same steps again first thing tomm as I felt it was the first tx which had the issue

**Comment by Eshwari007** [comment]
Also noticed in Explorer:
https://explorer.stacks.co/txid/0x7eab8eade7112a46444593f3c671deb7a7d840a7057cc98748184759cb6042af?chain=testnet

I transferred only 1 Stella but its indicating
<img width="409" alt="Screen Shot 2021-10-07 at 2 09 49 PM" src="https://user-images.githubusercontent.com/38872890/136439813-133a4355-76b7-4094-a132-c883ddc7cf7a.png">

**Comment by Eshwari007** [comment]
https://explorer.stacks.co/txid/0xd68febba322085d865e98391fa22ca302b94694addabba1d8f7a349fe2eeaf0b?chain=testnet

Same for the second Stella token transfer of 1

**Comment by Eshwari007** [comment]
I transffered 3.9 and its showing
<img width="890" alt="Screen Shot 2021-10-07 at 2 14 48 PM" src="https://user-images.githubusercontent.com/38872890/136440368-324dfd23-d2d6-4eab-b658-12b2d1c7161f.png">

**Comment by fbwoolf** [comment]
> @fbwoolf The first Stella token was `Queued` and then disappeared when I select `'Refresh"` on the screen. 

The queued state is just local state so it is expected that a refresh would clear it.

**Comment by Eshwari007** [comment]
https://user-images.githubusercontent.com/38872890/136467393-68c47055-f85f-413c-a6d3-cb0b2149dafa.mov

Adding video for perusal
cc @fbwoolf @beguene

**Comment by kyranjamie** [comment]
Unable to replicate. 

@Eshwari007 this example is quite stale, we've since made changes. If you can replicate again with a newer version, feel free to reopen.
