### ISSUE TITLE
Use a specific type when passing monetary values

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet-web#1797]
Throughout the wallet, we pass around units of account as either `string` or `BigNumber` types. This is probably a result of using values directly from the API.

An amount of STX, an FT, or any fiat currency **[is not just a number](https://www.martinfowler.com/eaaCatalog/money.html)**. It has a corresponding symbol that should always pair with a number. For accounting purposes, we can consider it money.

[See Rosetta implementation](https://www.rosetta-api.org/docs/api_objects.html#amount), where their API always returns monetary values along side information about the currency.

On a previous project, a [crypto exchange](https://bux-c.com/), we used an immutable `Money` type extensively and it worked great.

```ts
class Money { symbol: string; amount: BigNumber }
```

This helps some defensive programming techniques. Consider if we want to add to STX amounts together. `someStxValue.add(anotherStxValue)`. How can we be absolutely sure we're adding STX values together? I don't think we can currently.

Using a `Money` type, we can create functions like:

```ts
function addMoney(x: Money, y: Money) {
  if (x.symbol !== y.symbol) throw new Error('Cannot add amounts of different currencies');
  return x.amount.plus(y.amount);
}
```

To refactor this, we'd need to:
1) Add a core type representing units of money
2) Parse API responses to initialise values as the correct type
3) Refactor store to return values as these types

**Comment by beguene** [comment]
I completely agree with this. I also used a similar approach before and it works really well (and it's still simple)

**Comment by kyranjamie** [comment]
Closing as done, we're using `Money`
