### ISSUE TITLE
Add Account Labels to Hiro Wallet

### ISSUE THREAD

**Issue by andrerserrano** [blockstack/stacks-wallet-web#1832]
Add account labels to the web wallet, instead of "Account 1, Account 2, etc."

As the diversity of use cases on Stacks expands, it will be helpful to easily discern between accounts.

<img width="177" alt="Screen Shot 2021-10-13 at 3 36 09 PM" src="https://user-images.githubusercontent.com/44974743/137201255-b650db04-5ef2-47e9-b048-bb8bd824fafa.png">

**Comment by markmhendrickson** [comment]
Thanks for this recommendation. We're already tracking it in the following issue, so I'll close this one to consolidate: https://github.com/blockstack/stacks-wallet-web/issues/1703
