### ISSUE TITLE
Add Hardware Wallet support to Hiro Web Wallet

### ISSUE THREAD

**Issue by xanbots** [blockstack/stacks-wallet-web#1843]
Protocols are starting to launch on top of Stacks, and most, if not all of them will require the Hiro web wallet to interact. As an entity looking to potentially put a large amount of STX into some of these protocols, Daemon is worried about the lack of hardware security support in the web wallet. We consider this a problem that needs to be solved ASAP in order to enable success for the DeFi protocols launching in the future, given the known potential for vulnerabilities especially in browser extensions. I'm creating this issue in order to (1) raise awareness at Hiro about the pressing need, and (2) potentially rally the community to help with the development work needed if necessary. Thank you.

-Xan

**Comment by andresgalante** [comment]
Hi @xanbots, we are aware of the importance of adding ledger support to the web wallet and it's scheduled for us to start working during Q4. Hopefully, we'll have the feature out before the end of the year.

I'll close this issue in favor of this thread: https://github.com/blockstack/stacks-wallet-web/issues/951

**Comment by xanbots** [comment]
Perfect, thanks for letting me know Andres and for closing this in favor of the existing issue. Missed that.
