### ISSUE TITLE
Nonce error

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/stacks-wallet-web#1852]
This user sent a few txs within 5 mins of each other, never manually changed nonce, and their last transaction had the wrong nonce. 

address for details: 

https://explorer.stacks.co/txid/0xb58a2a8a5429fb6ee313e1408f6eb36edc8e0b360e3c5df85a13b963bbddfab9?chain=mainnet

**Comment by markmhendrickson** [comment]
Do you have the address by chance? The URL above appears to be for an unknown transaction.

**Comment by GinaAbrams** [comment]
Think related: https://github.com/blockstack/explorer/issues/578#issuecomment-952601301

**Comment by markmhendrickson** [comment]
Sounds good, should we close this one out then?
