### ISSUE TITLE
Increase fee is wrong on calculation

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/stacks-wallet-web#1858]
When increasing the fee on my transaction the calculation is incorrect. The fee loaded as `0.1136`, choosing `10x` changed the fee to `11.36`. Then choosing `1x` changes the fee to what it should have been at 10x, `1.136`. See images.

<img width="491" alt="Screen Shot 2021-10-24 at 11 54 34 AM" src="https://user-images.githubusercontent.com/6493321/138604484-a8a963c2-0163-48a4-863c-c3814ca58726.png">

<img width="487" alt="Screen Shot 2021-10-24 at 11 54 46 AM" src="https://user-images.githubusercontent.com/6493321/138604491-81c52bac-6c3a-4f7a-9730-769bf5668f8e.png">

<img width="486" alt="Screen Shot 2021-10-24 at 11 54 59 AM" src="https://user-images.githubusercontent.com/6493321/138604536-4e58d9d7-962b-40ff-938f-e48a13ba9a33.png">

**Comment by markmhendrickson** [comment]
Related: https://github.com/blockstack/stacks-wallet-web/issues/1649

**Comment by markmhendrickson** [comment]
Closing as stale
