### ISSUE TITLE
Wallet doesn't start after key phrase and password input

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/stacks-wallet-web#1861]
I have been seeing this kind of messages on the ALEX testnet discord:
![image](https://user-images.githubusercontent.com/33360391/138647099-3a79c132-9d9f-4599-88fb-eb6333f9ae38.png)

![image](https://user-images.githubusercontent.com/33360391/138647145-647daf10-c56a-4fab-b036-fa444e41ab12.png)

Incidentally this user is on Android and Kiwi browser, which I think is not yet supported.

**Comment by beguene** [comment]
Yes the web wallet is not supported on Android Kiwi browser, they should use Chrome or Firefox instead.
