### ISSUE TITLE
Refactor txForSettingsState

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/stacks-wallet-web#1874]
`txForSettingsState` is problematic, see code comment. We need to refactor it.

https://github.com/blockstack/stacks-wallet-web/blob/1dd04396dd26e263e4e967c8973f836f2e8f9be9/src/store/transactions/index.ts#L93

**Comment by kyranjamie** [comment]
@fbwoolf did you do this already right?

**Comment by fbwoolf** [comment]
Yep, I did. I will close this!
