### ISSUE TITLE
Same contract deployed twice with two different fee

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/stacks-wallet-web#2117]
PR:v2.24.0-beta.7

User running regression on the release version above in Mainnet

- User noticed that a contract deployed for a lower fee didnt get executed for a fee of 0.1
- User then deployed same contract for a fee of 0.4
-User noticed both contract (in same name) deployed twice once for 0.1 fee and another for 0.4

Assuming one contract will fail as both are in `Pending` state at the moment
<img width="501" alt="Screen Shot 2022-01-10 at 3 20 24 PM" src="https://user-images.githubusercontent.com/38872890/148835409-6a409128-277c-4dd7-bdd3-57cf51f34e5c.png">

Explorer link:
https://explorer.stacks.co/txid/0x50b99a6b90cbd68ebe39fa142ca9d187636e95b39746f39680e1ed96a99a62f2?chain=mainnet
https://explorer.stacks.co/txid/0x6147f2b8df6e970f22bd31b57e46202131829f0a64c44e58f0758e7bbb9cb2eb?chain=mainnet

**Comment by Eshwari007** [comment]
<img width="369" alt="Screen Shot 2022-01-11 at 11 14 07 AM" src="https://user-images.githubusercontent.com/38872890/148979795-4ba6c28b-203e-4b61-97fe-644bde5a7f6c.png">

Eventually one contract was stuck `Pending` which will fail eventually but the other contract was successful.Can we avoid came contract deployment with diff fees in some sort of validation check?

**Comment by markmhendrickson** [comment]
This seems like expected behavior in that we want users to be able to broadcast transactions that are similar yet slightly different (e.g. because of fees)
