### ISSUE TITLE
Add an info message in activity list

### ISSUE THREAD

**Issue by andresgalante** [blockstack/stacks-wallet-web#2187]
Add an info message in activity list so the user knows that the transaction can take some time (not few minutes)and they should be patient.

**Comment by Eshwari007** [comment]
@beguene Noticing an issue which I had seen previously in another PR(which got fixed)
Attaching the screenshot below: The send form is truncated in this PR

https://user-images.githubusercontent.com/38872890/152882555-660db39a-ee0e-4436-9fca-894a0bdd6717.mov

**Comment by Eshwari007** [comment]
@beguene also noticed just the Pending icon with info mark next to it and not the message
<img width="376" alt="Screen Shot 2022-02-07 at 5 26 32 PM" src="https://user-images.githubusercontent.com/38872890/152882796-d3464916-c80a-4bea-b088-0e14004fbf86.png">

**Comment by beguene** [comment]
@Eshwari007 Sorry my branch was not rebased, you can check it now.

**Comment by Eshwari007** [comment]
@beguene retested the issue and noticed that the info message visibility is less due to the message background color
<img width="571" alt="Screen Shot 2022-02-08 at 10 05 24 AM" src="https://user-images.githubusercontent.com/38872890/153014771-91e2fb72-ff02-4c77-b711-d425a7650871.png">
Is this the intended color?

**Comment by beguene** [comment]
@Eshwari007 No I will fix it.

**Comment by kyranjamie** [comment]
This was because tooltip styles were removed/added again. So we can just kill the styling added here.

**Comment by Eshwari007** [comment]
The info message is looking much better
<img width="580" alt="Screen Shot 2022-02-08 at 10 31 10 AM" src="https://user-images.githubusercontent.com/38872890/153020159-18d5c0f5-6009-467b-806e-cd72642963bf.png">
 cc @beguene @kyranjamie

**Comment by markmhendrickson** [comment]
cc @landitus for the informational design audit

**Comment by andresgalante** [comment]
@markmhx @landitus this feature is is part of the 3.2 release that will be out on Monday. If there aren't blocking design changes please lets make them after.

**Comment by markmhendrickson** [comment]
Yea my note was just for his separate audit effort. No need to make any more changes here for the release.
