### ISSUE TITLE
Update lock screen to match new onboarding

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/stacks-wallet-web#2199]
Update unlock screen to match new design:
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=2227%3A12789

![image](https://user-images.githubusercontent.com/6493321/152006777-74372dae-9a49-484d-883a-387f15f05f5b.png)

**Comment by fbwoolf** [comment]
@eugeniadigon is there a different (larger) illustration for the full page view? I only see the popup in the link.

**Comment by fbwoolf** [comment]
Also, as a note for QA, I don't think the back arrow here is correct. I am going to leave the current header which allows the user to sign out from this page.

**Comment by ginny-d** [comment]
Here's this step on full screen version
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=2594%3A13324

**Comment by Eshwari007** [comment]
@fbwoolf @eugeniadigon 

Attaching the figma design vs current implementation screenshot
On the design, it has the password in blue and in actual implementation it has 'Enter your password'.Which one should it go by?
<img width="846" alt="Screen Shot 2022-02-02 at 10 51 08 AM" src="https://user-images.githubusercontent.com/38872890/152189133-bddc370c-2f8a-4ff2-93bd-a3c6f7e7dfba.png">

P.S We have a ticket for the eye symbol(show or hide ) icon for all possible password entries

**Comment by ginny-d** [comment]
> @fbwoolf @eugeniadigon
> 
> Attaching the figma design vs current implementation screenshot On the design, it has the password in blue and in actual implementation it has 'Enter your password'.Which one should it go by? <img alt="Screen Shot 2022-02-02 at 10 51 08 AM" width="846" src="https://user-images.githubusercontent.com/38872890/152189133-bddc370c-2f8a-4ff2-93bd-a3c6f7e7dfba.png">
> 
> P.S We have a ticket for the eye symbol(show or hide ) icon for all possible password entries

I think this is the **focus** state for the input (what's shown on full screen) vs inactive state (what's showing on the extension screenshot)

**Comment by fbwoolf** [comment]
@Eshwari007 what you are pointing out will be part of redesigning the input overall for the app with this issue: https://github.com/hirosystems/stacks-wallet-web/issues/2198

**Comment by Eshwari007** [comment]
Thank you @fbwoolf Was going to upload a video that though the user is in the `focus` state or `inactive `state, the view is the same without the Password in blue indication.
@eugeniadigon #2198 was highlighted by Fara which will address the issue above.
