### ISSUE TITLE
.id names not showing up in identity list

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-wallet-web#2241]
My first several accounts should have ids associated with them.  account 1 should show 'dantrevino.id'.

![image](https://user-images.githubusercontent.com/7738/154084432-757a8765-c331-425c-b5db-353a5fc2c967.png)

**Comment by andresgalante** [comment]
@markmhx I'd like your help here since you know better why are are not supporting old .id names and what are the plans

**Comment by kyranjamie** [comment]
Is this a regression or a feature request?

**Comment by markmhendrickson** [comment]
This seems to be a regression in that `.id` names were loading last time I checked, but now I don't see them in my wallet either.

I looked up `dantrevino.id` here and it shows a different address oddly: https://stacks-node-api.mainnet.stacks.co/v1/names/dantrevino.id

<img width="870" alt="image" src="https://user-images.githubusercontent.com/28991/154444481-582d60d8-12e9-41e1-a69b-0b0086a828f5.png">

Note this result's address ends in `9XRP` and @dantrevino's screenshot's "Account 1" ends in `9WZS`.

The `9XRP` address also doesn't show up in the explorer: https://explorer.stacks.co/txid/SP1CQSE0KEWRXWQ34W2Y94H8407T2DRY3DMSA9XRP?chain=mainnet

@kyranjamie does the wallet use this endpoint to display usernames for accounts in this list, and if so, could this be an API-side issue with matching addresses to names?

**Comment by kyranjamie** [comment]
Seeing this issue, I do wonder if it's introduced by some of the changes in one of these PRs that fixes/refactors the slow render perf https://github.com/hirosystems/stacks-wallet-web/pull/2145, https://github.com/hirosystems/stacks-wallet-web/pull/2083, https://github.com/hirosystems/stacks-wallet-web/pull/2078

We use the addresses endpoint: 
https://stacks-node-api.stacks.co/v1/addresses/stacks/SP1CQSE0KEWRXWQ34W2Y94H8407T2DRY3DMSA9XRP

On our test address, it does seem to pull in id names
![image](https://user-images.githubusercontent.com/1618764/154452270-18503bc9-696c-4e04-8270-6eb43720c5b8.png)

**Comment by markmhendrickson** [comment]
That API also shows the mapping between `dantrevino.id` and `9XRP`, which appears incongruent with the address in his screenshot: https://stacks-node-api.stacks.co/v1/addresses/stacks/SP1CQSE0KEWRXWQ34W2Y94H8407T2DRY3DMSA9XRP

**Comment by markmhendrickson** [comment]
From @0xAsteria in Discord

<img width="685" alt="image" src="https://user-images.githubusercontent.com/28991/154645538-e339fd74-d43b-4661-ae9a-d464e1bc9c5f.png">

**Comment by dantrevino** [comment]
All of this is in the hiro wallet, which, afaik, only uses the hiro api server, which does import names.  The apps I've tested are also using hiro api server.

**Comment by zetrazetra** [comment]
Hi Mark, i was just checking via https://stacks-node-api.mainnet.stacks.co/v1/names/ the first .id (first address) from my old blockstack wallet and it has another address than the first Account that i get to see when login in to the new stacks wallet. Same with Account 2 etc.… So my old names don't seem to be connected to my old seedphrase or am i wrong here? Just wanted to make you aware for solving this problem. Have a nice sunday!

**Comment by markmhendrickson** [comment]
@zone117x @saralab any insight on whether a recent API change may have affected name/address mapping here?

**Comment by markmhendrickson** [comment]
Note that this is labeled P3 currently, though I'm tempted to upgrade it to P2 since it's near-critical for users to recognize their accounts upon selection. A significant number of power users (those with many accounts and registered usernames) may not be able to do so effectively at the moment given this bug.
