### ISSUE TITLE
Newly created  account toast isn't visible on wallet connecting to dApps 

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/stacks-wallet-web#2377]
Testing PR:2374

An issue with the new account toast, when testing connecting the wallet to a dApp. In this situation, the "account created" toast never appears.

https://user-images.githubusercontent.com/38872890/164243721-1176571c-bbaa-473e-8f07-2cee5a964cc0.mp4

**Comment by fbwoolf** [comment]
@Eshwari007 how can we communicate better about testing? I have already responded in numerous places that the toast not appearing is NOT an issue. The account is successfully created, correct? cc @andresgalante

**Comment by Eshwari007** [comment]
> @Eshwari007 how can we communicate better about testing? I have already responded in numerous places that the toast not appearing is NOT an issue. The account is successfully created, correct? cc @andresgalante

Agree, we need to improve communication around test findings, Best practice would be attaching the ticket which has already been created for the issue found.
For this example , a note that https://github.com/hirosystems/stacks-wallet-web/issues/2321 has already been created to address the issue , would help greatly . cc @andresgalante

**Comment by fbwoolf** [comment]
> > @Eshwari007 how can we communicate better about testing? I have already responded in numerous places that the toast not appearing is NOT an issue. The account is successfully created, correct? cc @andresgalante
> 
> Agree, we need to improve communication around test findings, Best practice would be attaching the ticket which has already been created for the issue found. For this example , a note that #2321 has already been created to address the issue , would help greatly . cc @andresgalante

This is noted on the original issue!!! https://github.com/hirosystems/stacks-wallet-web/issues/2370

**Comment by Eshwari007** [comment]
> > > @Eshwari007 how can we communicate better about testing? I have already responded in numerous places that the toast not appearing is NOT an issue. The account is successfully created, correct? cc @andresgalante
> > 
> > 
> > Agree, we need to improve communication around test findings, Best practice would be attaching the ticket which has already been created for the issue found. For this example , a note that #2321 has already been created to address the issue , would help greatly . cc @andresgalante
> 
> This is noted on the original issue!!! #2370

Thanks for bringing it up.I have started looking into it after you shared the link.
