### ISSUE TITLE
Nonce conflict, try again soon. (intermittent)

### ISSUE THREAD

**Issue by jcatama** [blockstack/stacks-wallet-web#2539]
**Describe the bug**
There is an intermittent issue where transaction is not being submitted (**Nonce conflict, try again soon**) while there is/are pending transaction/s.

Severity: Very low

Transaction ID: N/A
Address : N/A
Block#  : N/A
Time stamp: N/A

**To Reproduce**
1. Open the hiro wallet in a new tab.
2. Go to marketplace like gamma, and transfer any NFT to another wallet. (Maybe do this multiple times like 3-5 tx).
3. While the transfers are pending, try doing other tx like Transfer funds to the same wallet.
4. Intermittently, it should give you the nonce conflict error.

**Expected behavior**
Even though we can change the nonce manually, I believe this should be automatically handled with no issues.

**Screenshots**
<img width="516" alt="Screen Shot 2022-06-09 at 12 32 45 PM" src="https://user-images.githubusercontent.com/98573314/172765567-f1003712-8cf1-42d6-b7a5-925dfc65019c.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 12.4 (21F79)
 - Browser Chrome
 - Version 102.0.5005.61 (Official Build) (x86_64)

**Additional context**
Not a very important issue but this will serve as fyi.
Some people are experiencing this too.

**Comment by andresgalante** [comment]
This seems like an issue on the wallet, I'll transfer it to the wallet repo

**Comment by markmhendrickson** [comment]
@albrtctm Can you confirm whether you're seeing the same problem in the latest version of the wallet (v3.11.1)? We've improved how we handle nonces in general, so we may have resolved this for you by now.

**Comment by fbwoolf** [comment]
@albrtctm this was a known issue and should be fixed in v3.11.1.

**Comment by jcatama** [comment]
@markmhx @fbwoolf Tested and looks good! Kudos guys.

**Comment by fbwoolf** [comment]
Great to hear! I will close this issue then, thx for the feedback. 👍
