### ISSUE TITLE
Wallet freezes on "create new account"

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/stacks-wallet-web#2721]
Tested and seen on Firefox and Brave (Windows 10).

Steps
1. Open wallet
2. Login
3. Click upper left corner
4. Then Create address
5. see screen frozen and nothing happens

After the first freeze, closing the wallet screen, then opening it again clicking "create account" will make an additional account (almost) as expected (see: https://github.com/hirosystems/stacks-wallet-web/issues/2720)

**Comment by markmhendrickson** [comment]
Thanks for this report. Mind providing a screen recording of this issue as well so we can observe the exact behavior?

**Comment by 314159265359879** [comment]
I have not been able to consistently reproduce but I have seen it very often by now. I think especially when I have not used the extension for some time. Or after an update. The first login will have this issue. Once logged in, locking and logging in again is usually no issue. For example now I have restarted the browser several times to login again and no issue.

It happens on this screen after verify password, it will cycle through the additional message(s) "a bit more time" and the circle on the button will keep turning forever.
![image](https://user-images.githubusercontent.com/33360391/195806799-125dc265-d266-467c-a368-5cbd93067340.png)

**Comment by markmhendrickson** [comment]
If what you're seeing is that the password takes forever to verify, we have a PR under review that should hopefully fix it: https://github.com/hirosystems/stacks-wallet-web/pull/2666

By "wallet freezes", you mean to suggest that it's always freezing on this "Your session is locked" screen, correct?

**Comment by markmhendrickson** [comment]
@314159265359879 Have you seen this recently?

**Comment by 314159265359879** [comment]
I have not seen this recently. I believe it was fixed with 2666. Closing this.
