### ISSUE TITLE
Display Bitcoin Stamps in "Collectibles" area of home screen

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/stacks-wallet-web#3589]
In addition to displaying Ordinal inscriptions, BNS names and Stacks NFTs in the "Collectibles" area of the home screen, we should show Bitcoin Stamps as well. [See relevant code](https://github.com/hirosystems/wallet/blob/f5c8b1e3be397acb92a2e14247caf84d32e61c4f/src/app/features/collectibles/collectibles.tsx)

In theory there wouldn't have to be any UI changes aside from labeling them with "Bitcoin Stamp" and on hover omitting the "Send" button (until tackled separately):

<img width="956" alt="Screenshot 2023-04-24 at 14 01 07" src="https://user-images.githubusercontent.com/28991/233990950-d333eb85-e2ec-44e2-b225-aa490776347b.png">

<img width="218" alt="Screenshot 2023-04-24 at 14 01 41" src="https://user-images.githubusercontent.com/28991/233990960-e69b18d6-25c4-4fba-bc0d-ff5819a72a5e.png">

Clicking the arrow on hover could take the user to a stampchain.io (e.g. https://stampchain.io/asset.html?stampNumber=18478).

This API could be used to pull data on Stamps owned by the account's Native SegWit address: https://github.com/hydren-crypto/stampchain/blob/main/documentation/api.md

**Comment by mikeinspace** [comment]
Hey it's Mike from Bitcoin Stamps. We appreciate the efforts you've made in terms of integration.

Just wanted to bring your attention to our API documentation and new endpoints which should make queries a lot simpler.

https://github.com/hydren-crypto/stampchain/blob/main/docs/api.md

If you have any questions, we can schedule a call. I'm @mikeinspace on Twitter and Telegram.
