### ISSUE TITLE
Send brc20 to Btc addres (also stamp addres) how to fry the mint back to ordinal address

### ISSUE THREAD

**Issue by jithv198787** [blockstack/stacks-wallet-web#3780]

**Comment by 314159265359879** [comment]
Hi thanks for the tip. We actually had an issue for the enhancement to support sending ordinals to any address here https://github.com/hirosystems/wallet/issues/3670 some other issues came up and have gotten prioritized up to now. Def still something we want.

**Comment by markmhendrickson** [comment]
I believe @jithv198787 needs to "recover" the inscription here, which should be resolved by https://github.com/hirosystems/wallet/issues/3299 in which we support ordinals on the regular BTC address.
