### ISSUE TITLE
Improve icon DX

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet-web#4580]
Per Slack discussion on icons, opening issue. 

**Keeping DOM simple, allow underlying manipulation of svg**
Panda comes with a `styled.svg` and all all svg attributes as they're part of the HTML spec. This is powerful as we can pass tokens straight to SVGs. A wrapper isn't needed. Further, it prevents manipulation of the underlying SVG.

**Typing improvements**
For consistency with the design system, we now have icon sizes in size tokens. ~But with current impl, these aren't suggested~ Actually I was on an old panda build, but we could still narrow them further to only show the sizes we want to allow.
![image](https://github.com/leather-wallet/extension/assets/1618764/d8d0f1a4-7239-4fab-a613-17692cb50164)

We author these icons ourself, so why not narrow the type to only what we want to be able to use? 

```ts
size?: LiteralUnion<IconToken, string>; //using LiteralUnion to allow string while autocompleting literal values
```

**Comment by fbwoolf** [comment]
Thanks for the feedback @kyranjamie, I'll assign this to myself and get the icons refactored. 👍
