### ISSUE TITLE
Show USD values for Stacks FTs

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/stacks-wallet-web#4653]

**Comment by markmhendrickson** [comment]
@alter-eggo @fbwoolf Might one of you want to take this using the ALEX SDK for Stacks FTs and another for BRC-20 ones (e.g. perhaps Best in Slot, UniSat or CoinMarketCap's API)? It seems like a possible quick win ahead of redesigning the tokens UX in general.

Note that in addition to showing the USD values per token, we'd want to incorporate their values in the account total as well.

**Comment by fbwoolf** [comment]
Yep, sure, I can take it after my UI issues.

**Comment by fbwoolf** [comment]
@markmhendrickson is it ok just to handle what is returned by the alex-sdk for fiat prices?

```
{
    "age000-governance-token": 0.44284066666666666,
    "token-wusda": 0,
    "token-wstx": 3.48,
    "token-wban": 0.28039518,
    "token-wbtc": 69583.66666666667,
    "token-wdiko": 0.57905493,
    "token-wslm": 0.02933197,
    "token-wxusd": 0.9995446666666666,
    "token-wmia": 0,
    "token-wnycc": 0,
    "token-wcorgi": 0.00782047,
    "auto-alex-v2": 0.45748425875749976,
    "token-susdt": 1,
    "token-wvibes": 0.003541152750025805,
    "token-abtc": 68266.77159157977,
    "token-slunr": 0.23096300000000003,
    "brc20-chax": 0.00235852843073116,
    "token-wleo": 0.001848988570889095,
    "token-wmega-v2": 0.9843567751715196,
    "token-wgus": 0.00015734427742962597,
    "brc20-ordg": 0.3628395646699813,
    "brc20-ormm": 0.00028785
}
```

**Comment by markmhendrickson** [comment]
Yep that works

**Comment by fbwoolf** [comment]
@fabric-8 there are so many tokens being airdropped into wallets that don't have a fiat conversion available, should I just not show anything for now if `$0.00`?

<img width="904" alt="Screenshot 2024-03-27 at 8 24 29 PM" src="https://github.com/leather-wallet/extension/assets/6493321/9f213078-12db-4bea-aa61-95f02b662cd4">

**Comment by fabric-8** [comment]
I think displaying 0$ is ok, people might otherwise wonder wether any given token might actually be worth something and start looking around.

The more fundamental issue which we'll address is to not display spammy tokens in first place or give the user the option to hide those. I think we're planning to do that, @kyranjamie @markmhendrickson discussed this earlier this week

btw: can we just do $0 without the decimals? Makes it a bit faster to parse / less noisy :)

**Comment by markmhendrickson** [comment]
Let's just show blank? It's best not to give the impression that we know the value (or lack thereof) if we simply don't have the data

**Comment by fabric-8** [comment]
Ah, is there a difference between an unknown value and 0? I was assuming that we or the service we're using "knows" that the fiat value is 0

**Comment by fbwoolf** [comment]
> Ah, is there a difference between an unknown value and 0? I was assuming that we or the service we're using "knows" that the fiat value is 0

There is a difference in that that alex-sdk only returns data for a hand full of tokens, the others have no market data.

**Comment by fabric-8** [comment]
ok thanks for clarifying - Agree with Mark then 👍
