### ISSUE TITLE
Order of inscriptions flipped in latest update v6.43.0

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/stacks-wallet-web#5654]
With the latest v6.43.0 update, the order in which inscriptions show is now oldest to newest instead of newest to oldest.

I am not sure if this was intentional, but I think it is preferred to show the newest inscriptions at the top of your list rather than having to scroll to the bottom of your collectibles to see if you received something new, especially for large holders.

![Screenshot 2024-07-15 at 12 36 15 PM](https://github.com/user-attachments/assets/88fe51c2-7126-443f-a31c-a18c41495f41)

**Comment by kyranjamie** [comment]
Do we do any client side sorting, or could this be the API is returning in another order @alter-eggo ?

**Comment by alter-eggo** [comment]
@kyranjamie  yeah, I believe BiS returns them in other order
